import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { Nav } from "./_components/nav";
import { getServerAuthSession } from "~/server/auth";
import { ThemeProvider } from "next-themes";
import { Providers } from "./providers";
import MediaPlayer from "./_components/mediaPlayer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Music Profile T3",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <html lang="en">
      <body className="bg-vanila-brigh text-vanila h-[100svh] overflow-hidden">
        <TRPCReactProvider cookies={cookies().toString()}>
          <Providers>
            <div className="text-gray-dark dark:text-vanila flex h-full flex-col-reverse bg-white dark:bg-black sm:flex-row">
              {session && <Nav />}
              <main className="relative flex h-full w-full flex-col justify-between overflow-hidden overflow-y-auto duration-300 sm:opacity-[0.95]">
                {/* <section className="max-h-[calc(100%-5rem)] overflow-x-auto"> */}
                {children}
                {/* </section> */}
                {/* <section className="w-full h-20 border-t-2 border-gray  ">
                  <MediaPlayer />
                </section> */}
              </main>
            </div>
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
